### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by stucka** [PalmBeachPost/ntsb#2]
Reliance upon urllib2 breaks Python 3.

**Comment by dankeemahill** [comment]
The `unicode` [function calls](https://github.com/PalmBeachPost/ntsb/blob/master/fetchdocket.py#L47) also [don't exist in python 3](http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#unicode). Python3 can use the `str` function, but I'm not sure it will work the same in 2.

**Comment by stucka** [comment]
Thanks, @dankeemahill. I think it's good.
